name: Deploy a m2m.seypro.net.pe

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Instalar dependencias
        run: npm install

      - name: Build del frontend
        run: CI=false npm run build

      - name: Subir al dominio real (sin borrar .htaccess)
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 21
          protocol: ftp
          local-dir: ./build/
          server-dir: /domains/m2m.seypro.net.pe/public_html/
          strip-components: 1
          dangerous-clean-slate: true
          exclude: |
            .htaccess

      - name: Eliminar .ftp-deploy-sync-state.json
        run: |
          sudo apt-get update && sudo apt-get install -y lftp
          lftp -u ${{ secrets.FTP_USERNAME }},${{ secrets.FTP_PASSWORD }} -e "
            set ftp:list-options -a;
            cd /domains/m2m.seypro.net.pe/public_html/;
            rm .ftp-deploy-sync-state.json;
            bye
          " -p 21 ftp://${{ secrets.FTP_SERVER }}
